docsPath: ./myapp-docs
structure:
  summary: toc.md
  assets: assets
footerTemplate: ""
headerIncludes: ""
sites:
  - docsPath: nested/nested/docs/md
    structure:
      summary: toc2.md
      assets: files
