docsPath: ./myapp-docs
structure:
  summary: toc.md
  assets: assets
footerTemplate: ""
headerIncludes: ""
customCSS: ""
publishSpace: false
sites:
  - docsPath: nested/nested/docs/md
    structure:
      summary: toc2.md
      assets: files
    footerTemplate: ""
    headerIncludes: ""
    customCSS: ""
    customJS: ""
    publishSpace: false
